//#line 2 "/home/azisi/ros_catkin_ws/install_isolated/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the super_modified_servo package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __super_modified_servo__COMMANDERCONFIG_H__
#define __super_modified_servo__COMMANDERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace super_modified_servo
{
  class commanderConfigStatics;
  
  class commanderConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(commanderConfig &config, const commanderConfig &max, const commanderConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const commanderConfig &config1, const commanderConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, commanderConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const commanderConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, commanderConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const commanderConfig &config) const = 0;
      virtual void getValue(const commanderConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T commanderConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (commanderConfig::* field);

      virtual void clamp(commanderConfig &config, const commanderConfig &max, const commanderConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const commanderConfig &config1, const commanderConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, commanderConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const commanderConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, commanderConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const commanderConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const commanderConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, commanderConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, commanderConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<commanderConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(commanderConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("motor_id"==(*_i)->name){motor_id = boost::any_cast<int>(val);}
        if("new_motor_id"==(*_i)->name){new_motor_id = boost::any_cast<int>(val);}
        if("baudRate"==(*_i)->name){baudRate = boost::any_cast<int>(val);}
        if("p_gain"==(*_i)->name){p_gain = boost::any_cast<double>(val);}
        if("i_gain"==(*_i)->name){i_gain = boost::any_cast<double>(val);}
        if("d_gain"==(*_i)->name){d_gain = boost::any_cast<double>(val);}
        if("set_point"==(*_i)->name){set_point = boost::any_cast<double>(val);}
        if("command"==(*_i)->name){command = boost::any_cast<std::string>(val);}
      }
    }

    int motor_id;
int new_motor_id;
int baudRate;
double p_gain;
double i_gain;
double d_gain;
double set_point;
std::string command;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      int motor_id;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      int new_motor_id;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      int baudRate;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      double p_gain;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      double i_gain;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      double d_gain;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      double set_point;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      std::string command;
//#line 218 "/home/azisi/ros_catkin_ws/install_isolated/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("commanderConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const commanderConfig &__max__ = __getMax__();
      const commanderConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const commanderConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const commanderConfig &__getDefault__();
    static const commanderConfig &__getMax__();
    static const commanderConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const commanderConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void commanderConfig::ParamDescription<std::string>::clamp(commanderConfig &config, const commanderConfig &max, const commanderConfig &min) const
  {
    return;
  }

  class commanderConfigStatics
  {
    friend class commanderConfig;
    
    commanderConfigStatics()
    {
commanderConfig::GroupDescription<commanderConfig::DEFAULT, commanderConfig> Default("Default", "", 0, 0, true, &commanderConfig::groups);
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.motor_id = 4;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.motor_id = 255;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.motor_id = 5;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<int>("motor_id", "int", 0, "Motor ID", "", &commanderConfig::motor_id)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<int>("motor_id", "int", 0, "Motor ID", "", &commanderConfig::motor_id)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.new_motor_id = 4;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.new_motor_id = 255;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.new_motor_id = 5;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<int>("new_motor_id", "int", 0, "New motor ID", "", &commanderConfig::new_motor_id)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<int>("new_motor_id", "int", 0, "New motor ID", "", &commanderConfig::new_motor_id)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.baudRate = 600;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.baudRate = 115200;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.baudRate = 115200;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<int>("baudRate", "int", 0, "Set baud rate", "", &commanderConfig::baudRate)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<int>("baudRate", "int", 0, "Set baud rate", "", &commanderConfig::baudRate)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.p_gain = 0.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.p_gain = 600.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.p_gain = 0.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<double>("p_gain", "double", 0, "P gain", "", &commanderConfig::p_gain)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<double>("p_gain", "double", 0, "P gain", "", &commanderConfig::p_gain)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.i_gain = 0.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.i_gain = 600.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.i_gain = 0.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<double>("i_gain", "double", 0, "I gain", "", &commanderConfig::i_gain)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<double>("i_gain", "double", 0, "I gain", "", &commanderConfig::i_gain)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.d_gain = 0.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.d_gain = 600.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.d_gain = 0.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<double>("d_gain", "double", 0, "D gain", "", &commanderConfig::d_gain)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<double>("d_gain", "double", 0, "D gain", "", &commanderConfig::d_gain)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.set_point = -70.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.set_point = 90.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.set_point = 0.0;
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<double>("set_point", "double", 0, "Position set point", "", &commanderConfig::set_point)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<double>("set_point", "double", 0, "Position set point", "", &commanderConfig::set_point)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.command = "";
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.command = "";
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.command = "";
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<std::string>("command", "str", 0, "Send command", "", &commanderConfig::command)));
//#line 259 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(commanderConfig::AbstractParamDescriptionConstPtr(new commanderConfig::ParamDescription<std::string>("command", "str", 0, "Send command", "", &commanderConfig::command)));
//#line 233 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/home/azisi/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(commanderConfig::AbstractGroupDescriptionConstPtr(new commanderConfig::GroupDescription<commanderConfig::DEFAULT, commanderConfig>(Default)));
//#line 353 "/home/azisi/ros_catkin_ws/install_isolated/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<commanderConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<commanderConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<commanderConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    commanderConfig __max__;
    commanderConfig __min__;
    commanderConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const commanderConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static commanderConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &commanderConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const commanderConfig &commanderConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const commanderConfig &commanderConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const commanderConfig &commanderConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<commanderConfig::AbstractParamDescriptionConstPtr> &commanderConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<commanderConfig::AbstractGroupDescriptionConstPtr> &commanderConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const commanderConfigStatics *commanderConfig::__get_statics__()
  {
    const static commanderConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = commanderConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __COMMANDERRECONFIGURATOR_H__
